### PR TITLE
fix compare tests

### LINKED ISSUE #228: CI: Several `read_only_api_tests` are broken on master
```
Repositories: Test Failed at /home/runner/work/GitHub.jl/GitHub.jl/test/read_only_api_tests.jl:89
  Expression: (compare(ghjl, "master", "master~"; auth = auth)).behind_by == 1
   Evaluated: 7 == 1
```

```
Repositories: Test Failed at /home/runner/work/GitHub.jl/GitHub.jl/test/read_only_api_tests.jl:91
  Expression: comparison.ahead_by == 1
   Evaluated: 7 == 1
```

```
Repositories: Test Failed at /home/runner/work/GitHub.jl/GitHub.jl/test/read_only_api_tests.jl:92
  Expression: length(comparison.commits) == 1
   Evaluated: 7 == 1
```

---

Example PR:
- https://github.com/JuliaWeb/GitHub.jl/pull/226

Example CI log: https://github.com/JuliaWeb/GitHub.jl/actions/runs/15786277745/job/44503269205?pr=226

### PR DESCRIPTION
**Pull request by tanmaykm**
The compare tests failed if the commits on master branch were merge commits. This fixes the tests by checking the latest commit on master branch and changing the test conditions accordingly.

fixes  #228

### CODE REVIEW

File: test/read_only_api_tests.jl [hunk 1]
```diff
@@ -86,10 +86,21 @@ end
     @test hasghobj("master", first(branches(ghjl; auth = auth)))
 
     # test GitHub.compare
-    @test compare(ghjl, "master", "master~"; auth = auth).behind_by == 1
-    let comparison = compare(ghjl, "master~", "master"; auth = auth)
-        @test comparison.ahead_by == 1
-        @test length(comparison.commits) == 1
+    # check if the latest commit it a merge commit
```
Comment (DilumAluthge) [inline test/read_only_api_tests.jl:89]:
```suggestion
    # check if the latest commit is a merge commit
```

**Review by DilumAluthge — APPROVED** [review]

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
Thank you @tanmaykm!

File: test/read_only_api_tests.jl (hunk 1 above)
Comment (tanmaykm) [reply test/read_only_api_tests.jl]: thanks!
